// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButon: typeof import('element-plus/es')['ElButon']
    ElButton: typeof import('element-plus/es')['ElButton']
    Index: typeof import('./src/components/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/topBar/TopBar.vue')['default']
  }
}
